server {
    listen 80;
    server_name riserank.in www.riserank.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name riserank.in www.riserank.in;

    ssl_certificate /etc/letsencrypt/live/riserank.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/riserank.in/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/riserank;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin {
        alias /var/www/riserank-admin/dist;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }
}
